# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cerebus <cerebus@student.21-school.ru>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/05 11:22:16 by cerebus           #+#    #+#              #
#    Updated: 2020/11/22 16:51:05 by cerebus          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	libft.a
FLAGS	=	-Wall -Wextra -Werror
HEADER	=	libft.h
SRC		=	ft_atoi.c ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c\
			ft_isprint.c ft_memccpy.c ft_memchr.c ft_memcmp.c ft_memcpy.c\
			ft_memmove.c ft_memset.c ft_strchr.c ft_strlcat.c ft_strlcpy.c\
			ft_strlen.c ft_strncmp.c ft_strrchr.c ft_tolower.c ft_strnstr.c\
			ft_toupper.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c\
			ft_split.c ft_itoa.c ft_strmapi.c ft_putchar_fd.c ft_putstr_fd.c\
			ft_putendl_fd.c ft_putnbr_fd.c
BONUS	= 	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c\
			ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c\
			bonus.c

CC		=	gcc
OBJS	=	$(SRC:.c=.o)
BOBJS	=	$(BONUS:.c=.o)

.c.o:
			@$(CC) $(FLAGS) -g -c $< -o $(<:.c=.o)

$(NAME):	$(OBJS)
			@ar rc libft.a $(OBJS)

all:		$(NAME)

clean:
			@rm -f $(OBJS)

fclean:		clean
			@rm -f $(NAME)

re:			fclean all

bonus:		$(OBJS) $(BOBJS)
			@ar rc libft.a $(OBJS) $(BOBJS)

bfclean:
			@@rm -f $(NAME)
			
.PHONY:		all clean fclean re bonus bclean
